network: EfficientACTResnetEncoder
network_kwargs:
    pretrained: false
    freeze: false
    remove_layer_num: 4
    no_stride: false
    language_fusion: 'none'
    num_tok: 2 # number of tokens to reduce to
