# training
n_epochs: 100
batch_size: 32
num_workers: 4
grad_clip: 100.
loss_scale: 1.0
loss_type: "l1"

# resume training
resume: false
resume_path: ""
debug: true

use_augmentation: true

defaults:
    - optimizer@optimizer: adam_w.yaml
    - scheduler@scheduler: cosine_annealing.yaml
