# @package _global_

defaults:
  - data: default
  - policy: skill_GPT
  - train: default
  - eval: default
  - lifelong: multitask
  - test: null
  # - override policy/image_encoder: dino_encoder.yaml
  # - override policy/data_augmentation@policy.color_aug: identity_aug.yaml
  # - override policy/data_augmentation@policy.color_aug: identity_aug.yaml
  - _self_

# change defaults
data:
  seq_len: 96
  obs_seq_len: 1
eval:
  eval: true
  n_eval: 40
  num_procs: 5
  batch_size: 128
  num_workers: 6

pretrain_skillVAE_path: null
pretrain_model_path: "/satassdscratch/amete7/LIBERO/experiments_clip/LIBERO_90/Multitask/SkillGPT_Model/ResnetEncoder/m4no_single_stack_n6d384_off10_nobugs/run_001/multitask_model_ep80.pth"
exp_name: "eval_m4_32_f4_k3s4_tt_5shot_e20"
seed: 1000
use_wandb: false
wandb_project: "diff-skill-libero"
folder: null # use default path
bddl_folder: null # use default path
init_states_folder: null # use default path
load_previous_model: false
tune_decoder: false
device: "cuda"
task_embedding_format: "clip"
task_embedding_one_hot_offset: 1
pretrain: false
benchmark_name: "LIBERO_90"
