# @package _global_

defaults:
  - data: default
  - policy: skill_vae
  - train: default
  - eval: default
  - lifelong: multitask
  - test: null
  - _self_

# change defaults
data:
  seq_len: 32
  obs_seq_len: 1
eval:
  eval: false
train:
  batch_size: 512
  num_workers: 6df
  n_epochs: 100

seed: 10000
use_wandb: false
wandb_project: "diff-skill-libero"
folder: null # use default path
bddl_folder: null # use default path
init_states_folder: null # use default path
load_previous_model: false
device: "cuda"
task_embedding_format: "clip"
task_embedding_one_hot_offset: 1
pretrain: true
pretrain_model_path: ""
benchmark_name: "LIBERO_10"
