# @package _global_

defaults:
  - data: default
  - policy: skill_GPT
  - train: default
  - eval: default
  - lifelong: multitask
  - test: null
  - _self_

# change defaults
data:
  seq_len: 32
  obs_seq_len: 1
eval:
  eval: false
lifelong:
  eval_in_train: false
train:
  batch_size: 256
  num_workers: 6
  n_epochs: 100
policy:
  use_m4: 1
  cross_z: true
  vq_type: "fsq"
  fsq_level: [8,5,5,5]
  use_causal_decoder: true
  strides: [2,2,1]

pretrain_skillVAE_path: "/satassdscratch/amete7/LIBERO/experiments_clip/LIBERO_90/Multitask_Pretrain/SkillVAE_Model/ResnetEncoder/m4_32_f4_k3s4_tt/run_001/multitask_model_ep100.pth"
exp_name: "m4_32_f4_k3s4_tt_n6d384" # n6d384: GPT model num_heads=num_layers=6, d_model=384
seed: 10000
use_wandb: true
wandb_project: "diff-skill-libero"
folder: null # use default path
bddl_folder: null # use default path
init_states_folder: null # use default path
load_previous_model: false
device: "cuda"
task_embedding_format: "clip"
task_embedding_one_hot_offset: 1
pretrain: false
pretrain_model_path: ""
benchmark_name: "LIBERO_90"
