# @package _global_

defaults:
  - data: default
  - policy: vq_bet
  - train: default
  - eval: default
  - lifelong: multitask
  - test: null
  - _self_

# change defaults
data:
  seq_len: 10
  obs_seq_len: 10
eval:
  eval: false
  eval_every: 50
train:
  batch_size: 256
  num_workers: 6
  n_epochs: 300
policy:
  skill_block_size: 1

pretrain_vqvae_path: "/ssdscratch/amete7/LIBERO/experiments_clip/LIBERO_10/Multitask_Pretrain/VQVAE_Model/ResnetEncoder/vqbet_a1_l1h128_c16_n2/run_001/multitask_model_ep300.pth"
exp_name: "vqbet_a1_l1h128_c16_n2_n6d120" # n6d384: GPT model num_heads=num_layers=6, d_model=384
seed: 10000
use_wandb: false
wandb_project: "diff-skill-libero"
folder: null # use default path
bddl_folder: null # use default path
init_states_folder: null # use default path
load_previous_model: false
tune_decoder: false
device: "cuda"
task_embedding_format: "clip"
task_embedding_one_hot_offset: 1
pretrain: false
pretrain_model_path: ""
benchmark_name: "LIBERO_10"
