policy_type: Diffusion_Policy
extra_num_layers: 0
extra_hidden_size: 32
extra_embedding_size: 32 # joint_states emb size is twice this value

action_dim: 7
obs_emb_dim: 256 # from 512 to this value using MLP
cat_obs_dim: 640 # 256 + 256 + 32 + 32 + 64 (front_cam, gripper_cam, gripper_state (2), gripper_pos (3), joint_states (7))
skill_block_size: 32 # this is input sequence length to encoder

global_cond_dim: 1152 # 640 + 512 (lang_emb_dim)
diffusion_step_embed_dim: 256
down_dims: [256,512,1024]

scheduler: 'ddim' # 'ddpm' or 'ddim'
diffusion_train_steps: 100
diffusion_inf_steps: 10
ema_power: 0.75

lang_emb_dim: 512 # clip embedding size
mpc_horizon: 16 # mpc horizon for execution

defaults:
    - data_augmentation@color_aug: batch_wise_img_color_jitter_group_aug.yaml
    - data_augmentation@translation_aug: translation_aug.yaml
    - image_encoder: resnet_encoder.yaml
    - language_encoder: mlp_encoder.yaml
