policy_type: SkillGPT_Model
extra_num_layers: 0
extra_hidden_size: 32
extra_embedding_size: 32 # joint_states emb size is twice this value
obs_emb_dim: 256 # from 512 to this value using MLP
cat_obs_dim: 640 # 256 + 256 + 32 + 32 + 64 (front_cam, gripper_cam, gripper_state (2), gripper_pos (3), joint_states (7))
action_dim: 7

prior:
    start_token: 1015
    offset_layers: 0
    offset_hidden_dim: 512

    vocab_size_1: 15
    vocab_size_2: 1000
    block_size_1: 4
    block_size_2: 8
    
    n_layer: 6
    n_head: 6
    n_embd: 384
    attn_pdrop: 0.1
    embd_pdrop: 0.1
    beam_size: 5 # value of k for top k sampling
    temperature: 1.0 # temperature for sampling

skill_vae_1:
    path: "/satassdscratch/amete7/LIBERO/experiments_clip/LIBERO_90/Multitask_Pretrain/SkillVAE_Model/ResnetEncoder/m4no_96_f2_k9s24_tt/run_001/multitask_model_ep100.pth"
    action_dim: 7
    encoder_dim: 256
    decoder_dim: 256
    skill_block_size: 96 # this is input sequence length to encoder

    encoder_heads: 4
    encoder_layers: 2
    decoder_heads: 4
    decoder_layers: 4

    attn_pdrop: 0.1
    use_causal_encoder: true
    use_causal_decoder: true

    vq_type: "fsq" # "vq" or "fsq"
    fsq_level: [5,3]
    codebook_dim: 512 # only used for vq
    codebook_size: 1024 # only used for vq

    kernel_sizes: [5,3,3,3,3,3,3,3,3] # conv module will have 3 layers with kernel sizes 5,3,3
    strides: [1,1,2,1,2,1,2,1,3] # conv module will have 3 layers with strides 2,2,1

skill_vae_2:
    path: "/satassdscratch/amete7/LIBERO/experiments_clip/LIBERO_90/Multitask_Pretrain/SkillVAE_Model/ResnetEncoder/m4no_32_f4_k3s4_tt/run_001/multitask_model_ep100.pth"
    action_dim: 7
    encoder_dim: 256
    decoder_dim: 256
    skill_block_size: 32 # this is input sequence length to encoder

    encoder_heads: 4
    encoder_layers: 2
    decoder_heads: 4
    decoder_layers: 4

    attn_pdrop: 0.1
    use_causal_encoder: true
    use_causal_decoder: true

    vq_type: "fsq" # "vq" or "fsq"
    fsq_level: [8,5,5,5]
    codebook_dim: 512 # only used for vq
    codebook_size: 1024 # only used for vq

    kernel_sizes: [5,3,3] # conv module will have 3 layers with kernel sizes 5,3,3
    strides: [2,2,1] # conv module will have 3 layers with strides 2,2,1

offset_loss_scale: 0.0
lang_emb_dim: 512 # clip embedding size
mpc_horizon: 24 # mpc horizon for execution

defaults:
    - data_augmentation@color_aug: batch_wise_img_color_jitter_group_aug.yaml
    - data_augmentation@translation_aug: translation_aug.yaml
    - image_encoder: resnet_encoder.yaml
    - language_encoder: mlp_encoder.yaml
