policy_type: SkillGPT_Model
extra_num_layers: 0
extra_hidden_size: 32
extra_embedding_size: 32 # joint_states emb size is twice this value

cross_z: true # decoder cross attends to z
use_m4: 1 # when m4 is set to 1, the decoder also cross attends to observation
action_dim: 7
obs_emb_dim: 256 # from 512 to this value using MLP
cat_obs_dim: 640 # 256 + 256 + 32 + 32 + 64 (front_cam, gripper_cam, gripper_state (2), gripper_pos (3), joint_states (7))
encoder_dim: 256
decoder_dim: 256
skill_block_size: 32 # this is input sequence length to encoder

encoder_heads: 4
encoder_layers: 4
decoder_heads: 4
decoder_layers: 4

resid_pdrop: 0.1
attn_pdrop: 0.1
use_causal_encoder: true
use_causal_decoder: true

vq_type: "fsq" # "vq" or "fsq"
fsq_level: [8,5,5,5]
codebook_dim: 512 # only used for vq
codebook_size: 1024 # only used for vq

kernel_sizes: [5,3,3] # conv module will have 3 layers with kernel sizes 5,3,3
strides: [2,2,1] # conv module will have 3 layers with strides 2,2,1

defaults:
    - data_augmentation@color_aug: batch_wise_img_color_jitter_group_aug.yaml
    - data_augmentation@translation_aug: translation_aug.yaml
    - image_encoder: resnet_encoder.yaml
    - language_encoder: mlp_encoder.yaml